In [36]:
import pandas as pd

In [37]:
df = pd.read_csv('data/data.csv')
df.head()

,ID,artist_name,track_name,track_id,popularity,year,genre,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,duration_ms,time_signature
0,1770,Neon Trees,Everybody Talks,2iUmqdfGZcHIhS3b9E9EWq,77,2012,alt-rock,0.471,0.924,8,-3.906,1,0.0586,0.00301,0.000000,0.3130,0.7250,154.961,177280,4
1,1771,Deftones,Rosemary,4FEr6dIdH6EqLKR0jB560J,71,2012,alt-rock,0.285,0.613,5,-6.412,1,0.0421,0.01850,0.100000,0.1140,0.0772,126.628,413347,4
2,1773,Thousand Foot Krutch,Courtesy Call,0AOmbw8AwDnwXhHC3OhdVB,71,2012,alt-rock,0.531,0.638,11,-5.145,0,0.0809,0.00409,0.000000,0.0822,0.4450,164.079,236898,4
3,1816,Vicentico,No Te Apartes de Mí,74KqkyHbpneHF6JT8EwUOO,70,2012,alt-rock,0.816,0.549,7,-8.649,1,0.0312,0.79100,0.000034,0.1170,0.8860,111.032,198333,4
4,12104,Bruno Mars,Locked out of Heaven,3w3y8KPTfNeOKPiqUTakBh,85,2012,dance,0.726,0.698,5,-4.165,1,0.0431,0.04900,0.000000,0.3090,0.8670,143.994,233478,4

In [38]:
df_clean = df.drop(['track_id', 'loudness', 'mode', 'speechiness', 'acousticness', 'instrumentalness', 'liveness', 'duration_ms', 'time_signature'], axis=1)
df_clean.head()

,ID,artist_name,track_name,popularity,year,genre,danceability,energy,key,valence,tempo
0,1770,Neon Trees,Everybody Talks,77,2012,alt-rock,0.471,0.924,8,0.7250,154.961
1,1771,Deftones,Rosemary,71,2012,alt-rock,0.285,0.613,5,0.0772,126.628
2,1773,Thousand Foot Krutch,Courtesy Call,71,2012,alt-rock,0.531,0.638,11,0.4450,164.079
3,1816,Vicentico,No Te Apartes de Mí,70,2012,alt-rock,0.816,0.549,7,0.8860,111.032
4,12104,Bruno Mars,Locked out of Heaven,85,2012,dance,0.726,0.698,5,0.8670,143.994

In [39]:
df = df_clean.groupby(['year', 'genre'])
df.head(50)

,ID,artist_name,track_name,popularity,year,genre,danceability,energy,key,valence,tempo
0,1770,Neon Trees,Everybody Talks,77,2012,alt-rock,0.471,0.924,8,0.7250,154.961
1,1771,Deftones,Rosemary,71,2012,alt-rock,0.285,0.613,5,0.0772,126.628
2,1773,Thousand Foot Krutch,Courtesy Call,71,2012,alt-rock,0.531,0.638,11,0.4450,164.079
3,1816,Vicentico,No Te Apartes de Mí,70,2012,alt-rock,0.816,0.549,7,0.8860,111.032
4,12104,Bruno Mars,Locked out of Heaven,85,2012,dance,0.726,0.698,5,0.8670,143.994
...,...,...,...,...,...,...,...,...,...,...,...
3313,1296636,Kid Cudi,Day 'N' Nite (nightmare),70,2009,hip-hop,0.881,0.441,11,0.8040,138.014
3314,1296637,Drake,Forever,72,2009,hip-hop,0.457,0.906,5,0.5400,104.020
3315,1296645,Eminem,Crack A Bottle,70,2009,hip-hop,0.516,0.874,9,0.3910,169.561
3316,1296647,Eminem,Beautiful,70,2009,hip-hop,0.727,0.696,5,0.4670,132.077
3317,1296748,Imran Khan,Bewafa,70,2009,hip-hop,0.704,0.563,4,0.0739,94.037

In [40]:
df.to_csv('cleanData.csv')

AttributeError: 'DataFrameGroupBy' object has no attribute 'to_csv'